---
#============================================================================
# This file contains the configuration for the build.js script which
# generates a custom library of Fontawesome 6 icons.  This is used by the
# Icon component in src/components/Icon.
#
# After making any changes here or adding any files to the "custom" directory
# you should run the build.js script to generate a new icon library. You can
# run the script in the cog-ui library using this yarn command:
#
#   yarn icons
#
# If you're running it from a project which uses cog-ui then it would be:
#
#   node node_modules/cog-ui/icons/build.js --verbose --extend
#
# See the README.md file for further information.
#============================================================================

sets:
  # icons to include from solid icon set
  solid:
    - angle-left
    - angle-right
    - angle-down
    - angle-up
    - arrow-up
    - arrow-down
    - arrow-left
    - arrow-right
    - asterisk
    - at
    - ban
    - bars
    - caret-up
    - caret-down
    - caret-left
    - caret-right
    - cat
    - check
    - circle
    - circle-exclamation
    - circle-question
    - clipboard-list
    - filter
    - grip-vertical
    - key
    - plus
    - radiation
    - sort
    - sort-down
    - sort-up
    - rotate-left
    - toggle-on
    - toggle-off
    - trash
    - user
    - users
    - wrench

  # icons to include from regular icon set
  regular:
    - circle-check
    - circle-dot
    - face-frown
    - square

  # include all custom icons
  custom: '*'


  # define icon name mapping
icons:
  alert:        solid:circle-exclamation
  checkbox-on:  solid:square-check
  checkbox-off: regular:square
  check-circle: solid:circle-check
  check-ring:   regular:circle-check
  ring:         regular:circle
  cogs:         solid:gears
  happy:        regular:face-smile
  info:         solid:circle-info
  info-circle:  solid:circle-info
  ok:           solid:circle-check
  radio-on:     regular:circle-dot
  radio-off:    regular:circle
  sad:          regular:face-frown
  search:       solid:magnifying-glass
  times:        solid:xmark
  times-circle: solid:circle-xmark
  times-ring:   regular:circle-xmark
  undo:         solid:rotate-left
  warning:      solid:triangle-exclamation
