---
#============================================================================
# This file contains the configuration for the build.js script which
# generates a custom library of Fontawesome 6 icons.  This is used by the
# Icon component in src/components/Icon.
#
# After making any changes here or adding any files to the "custom" directory
# you should run the build.js script to generate a new icon library. You can
# run the script in the cog-ui library using this yarn command:
#
#   yarn icons
#
# If you're running it from a project which uses cog-ui then it would be:
#
#   node node_modules/cog-ui/icons/build.js --verbose --extend
#
# See the README.md file for further information.
#============================================================================

sets:
  # icons to include from solid icon set
  solid:
    - angle-left
    - angle-right
    - angle-down
    - angle-up
    - arrow-up
    - arrow-down
    - arrow-left
    - arrow-right
    - asterisk
    - at
    - ban
    - bars
    - caret-up
    - caret-down
    - caret-left
    - caret-right
    # - square-caret-left
    # - square-caret-right
    - cat
    - check
    # - square-check
    - circle
    - circle-check
    - circle-exclamation
    - circle-question
    # - cog
    # - cogs
    - clipboard-list
    # - exclamation-triangle
    - filter
    - grip-vertical
    # - info-circle
    - key
    - plus
    - radiation
    - sort
    - sort-down
    - sort-up
    - rotate-left
    - toggle-on
    - toggle-off
    - trash
    - user
    - users
    - wrench

  # icons to include from regular icon set
  regular:
    - circle-check
    - circle-dot
    - face-frown
    - square

  # include all custom icons
  custom: '*'


  # define aliases for icons
icons:
  alert:        solid:circle-exclamation
  checked:      solid:square-check
  check-circle: regular:circle-check
  ring:         regular:circle
  # cog:          solid:gear
  cogs:         solid:gears
  dotted:       regular:circle-dot
  dot-circle:   regular:circle-dot
  info:         solid:circle-info
  ok:           solid:circle-check
  sad:          regular:face-frown
  search:       solid:magnifying-glass
  times:        solid:xmark
  times-circle: solid:circle-xmark
  unchecked:    regular:square
  undo:         solid:rotate-left
  undotted:     regular:circle
  warning:      solid:triangle-exclamation

# # set true if you want to automatically generate aliases for regular icons
# aliasRegular: true
#
# # load all custom icons in the 'custom' directory (relative to this dir)
# customDir: custom
